// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRHdWIrGB2F9wZTubOypZQ6fnd4eShDEs',
    appId: '1:1020144734149:web:de8efa97c85836c65045ac',
    messagingSenderId: '1020144734149',
    projectId: 'inst-clone-ba52d',
    authDomain: 'inst-clone-ba52d.firebaseapp.com',
    storageBucket: 'inst-clone-ba52d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBSDunaoBpoKWQ1HR8eYpFH3QKYNqTMbM',
    appId: '1:1020144734149:android:c99cc30509faf21a5045ac',
    messagingSenderId: '1020144734149',
    projectId: 'inst-clone-ba52d',
    storageBucket: 'inst-clone-ba52d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxY1sS8KytA9yA7Q7J2oKOb6dSLWe_-U',
    appId: '1:1020144734149:ios:95ea11f7c043600a5045ac',
    messagingSenderId: '1020144734149',
    projectId: 'inst-clone-ba52d',
    storageBucket: 'inst-clone-ba52d.appspot.com',
    iosClientId: '1020144734149-6103jl8c6e9u4tgrpmb65i6hhpnte7pp.apps.googleusercontent.com',
    iosBundleId: 'com.aopb.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxY1sS8KytA9yA7Q7J2oKOb6dSLWe_-U',
    appId: '1:1020144734149:ios:95ea11f7c043600a5045ac',
    messagingSenderId: '1020144734149',
    projectId: 'inst-clone-ba52d',
    storageBucket: 'inst-clone-ba52d.appspot.com',
    iosClientId: '1020144734149-6103jl8c6e9u4tgrpmb65i6hhpnte7pp.apps.googleusercontent.com',
    iosBundleId: 'com.aopb.instagramClone',
  );
}
